analytics: {}
color:
  brandColors:
    - '#E0E8E0'
    - '#185898'
    - '#6878A0'
    - '#C82028'
    - '#C88088'
  brandStrength: 0.3125
  lightness: 0.4375
  rhythmicContrast: 0.5
  saturation: 0.625
cta: {}
layout_spectrum: 0.37621
name: Multimedia Design Scientist
opengraph: {}
purpose: []
typography_spectrum: 0.13532
