name: Multimedia Design Scientist
favicon: null
layout_spectrum: 0.58724
typography_spectrum: 0.4009
title: Multimedia Design Scientist Nathaniel Hafer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#e3e3e3'
    - '#925554'
    - '#82b371'
    - '#395b81'
  brandStrength: 0.892867011250928
  lightness: 0.3125
  saturation: 0.3702758711297065
  rhythmicContrast: 0.5
purpose: []
