name: Multimedia Design Scientist
favicon: null
layout_spectrum: 0.11063
typography_spectrum: 0.12448
title: Multimedia Design Scientist Nathaniel Hafer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#e3e3e3'
    - '#925554'
    - '#82b371'
    - '#395b81'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
