name: Multimedia Design Scientist
favicon: null
layout_spectrum: 0.3727512320037931
typography_spectrum: 0.6664944265503436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.892867011250928
  lightness: 0.31904500303789973
  saturation: 0.3702758711297065
  rhythmicContrast: 0.05182320368476212
purpose: []
