name: Multimedia Design Scientist
favicon: null
layout_spectrum: 0.09256
typography_spectrum: 0.12768
title: Nathaniel Hafer - Multimedia Design Scientist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#e3e3e3'
    - '#925554'
    - '#82b371'
    - '#395b81'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
